image: clord/restedpi-ci

before_script:
  - export DEBIAN_FRONTEND=noninteractive

stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths: 
      - target/release

  script: cargo build --target=armv7-unknown-linux-gnueabihf --release

test:
  stage: build
  script: cargo build
  script: 
    - sleep 10 
    - cargo test

deploy:
  stage: deploy
  only:
    - master
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ls target/release/*
    - rsync -hrvz --delete target/release/restedpi $DEPLOY_USER@$DEPLOY_HOST:/usr/local/bin/restedpi

