image: clord/restedpi-ci
stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: cargo build

test:
  stage: test
  script: cargo test

deploy:
  stage: deploy
  only:
    - master
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - cargo build --target=armv7-unknown-linux-gnueabihf --release
    - ls -la target/*
    #    - rsync -hrvz --delete  $DEPLOY_USER@$DEPLOY_HOST

