keys:
  - &admin_clord age1d870exktlqqx27jns4ls2zkes6rf8hsus4aechytkrxk8nk5kg3svdgsqg
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_clord
