/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RouterHistory } from "@stencil/router";
export namespace Components {
    interface AddDevice {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface ListConfiguredDevices {
    }
    interface SetupDevices {
        "history": RouterHistory;
    }
}
declare global {
    interface HTMLAddDeviceElement extends Components.AddDevice, HTMLStencilElement {
    }
    var HTMLAddDeviceElement: {
        prototype: HTMLAddDeviceElement;
        new (): HTMLAddDeviceElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLListConfiguredDevicesElement extends Components.ListConfiguredDevices, HTMLStencilElement {
    }
    var HTMLListConfiguredDevicesElement: {
        prototype: HTMLListConfiguredDevicesElement;
        new (): HTMLListConfiguredDevicesElement;
    };
    interface HTMLSetupDevicesElement extends Components.SetupDevices, HTMLStencilElement {
    }
    var HTMLSetupDevicesElement: {
        prototype: HTMLSetupDevicesElement;
        new (): HTMLSetupDevicesElement;
    };
    interface HTMLElementTagNameMap {
        "add-device": HTMLAddDeviceElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "list-configured-devices": HTMLListConfiguredDevicesElement;
        "setup-devices": HTMLSetupDevicesElement;
    }
}
declare namespace LocalJSX {
    interface AddDevice {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface ListConfiguredDevices {
    }
    interface SetupDevices {
        "history"?: RouterHistory;
    }
    interface IntrinsicElements {
        "add-device": AddDevice;
        "app-home": AppHome;
        "app-root": AppRoot;
        "list-configured-devices": ListConfiguredDevices;
        "setup-devices": SetupDevices;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-device": LocalJSX.AddDevice & JSXBase.HTMLAttributes<HTMLAddDeviceElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "list-configured-devices": LocalJSX.ListConfiguredDevices & JSXBase.HTMLAttributes<HTMLListConfiguredDevicesElement>;
            "setup-devices": LocalJSX.SetupDevices & JSXBase.HTMLAttributes<HTMLSetupDevicesElement>;
        }
    }
}
